import { useState, useEffect, useRef } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { Navigation } from "@/components/ui/navigation";
import { FeedSection } from "@/components/eco/feed-section";
import { ExploreSection } from "@/components/eco/explore-section";
import { CarbonDashboard } from "@/components/eco/carbon-dashboard";
import { UserProfile } from "@/components/eco/user-profile";
import { FloatingActionButton } from "@/components/eco/floating-action-button";
import { RegisterActionModal } from "@/components/eco/register-action-modal";
import { LoginModal } from "@/components/eco/login-modal";
import { toast } from "@/hooks/use-toast";

const Index = () => {
  // Mock data - moved up to fix declaration order
  const mockPosts = [
    {
      user: { name: "Carlos Verde", username: "carlos_v", avatar: undefined },
      content: "Hoy caminé al trabajo en lugar de usar el auto. 30 minutos de ejercicio y aire fresco mientras cuido el planeta 🚶‍♂️🌱",
      co2Impact: 2.1,
      actionType: "transport" as const,
      likes: 15,
      comments: 3,
      isLiked: false,
      timestamp: "hace 2h",
      hasSustainableAction: true,
    },
    {
      user: { name: "María Sustentable", username: "maria_sust", avatar: undefined },
      content: "Preparé una comida vegana deliciosa con vegetales locales. La quinoa con verduras asadas quedó increíble 🥗✨",
      co2Impact: 1.8,
      actionType: "food" as const,
      likes: 23,
      comments: 7,
      isLiked: true,
      timestamp: "hace 4h",
      hasSustainableAction: true,
    },
    {
      user: { name: "Luis Ecológico", username: "luis_eco", avatar: undefined },
      content: "Instalé paneles solares en casa. La inversión inicial vale la pena por el ahorro energético a largo plazo ☀️⚡",
      co2Impact: 5.2,
      actionType: "energy" as const,
      likes: 32,
      comments: 12,
      isLiked: false,
      timestamp: "hace 1d",
      hasSustainableAction: true,
    },
  ];

  const [activeTab, setActiveTab] = useState("feed");
  const [posts, setPosts] = useState(mockPosts);
  const [showRegisterModal, setShowRegisterModal] = useState(false);
  const [currentUser, setCurrentUser] = useState<{name: string, username: string, avatar?: string} | null>(null);
  const [autoGeneratedPosts, setAutoGeneratedPosts] = useState<any[]>([]);
  const navigate = useNavigate();
  const location = useLocation();
  const intervalRef = useRef<NodeJS.Timeout | null>(null);

  // Handle navigation based on tab selection
  const handleTabChange = (tab: string) => {
    setActiveTab(tab);
    if (tab === "benefits") {
      navigate("/benefits");
    }
    // Other tabs stay on the main page
  };

  // Set active tab based on current route
  useEffect(() => {
    if (location.pathname === "/benefits") {
      setActiveTab("benefits");
    } else {
      // Default to feed for main page
      setActiveTab("feed");
    }
  }, [location.pathname]);

  // Persist user session in localStorage
  useEffect(() => {
    const savedUser = localStorage.getItem('ecoways-user');
    if (savedUser) {
      setCurrentUser(JSON.parse(savedUser));
    }
  }, []);

  // Auto-generate posts every 10 seconds when user is logged in
  useEffect(() => {
    if (!currentUser) return;

    const generateRandomPost = () => {
      const users = [
        "Ana Verde", "Pedro Sustentable", "Laura Eco", "Diego Limpio", 
        "Sofia Natura", "Miguel Solar", "Carmen Bio", "Andrés Recicla"
      ];
      const actions = [
        "Usé transporte público hoy, reduciendo mis emisiones 🚌",
        "Comí vegano todo el día, ¡delicioso y sostenible! 🌱",
        "Recicle toda mi basura de la semana correctamente ♻️",
        "Ahorré agua con duchas más cortas 🚿💧",
        "Cambié a bombillas LED en toda mi casa 💡",
        "Usé mi bicicleta para ir al trabajo 🚲",
        "Compré productos locales en el mercado 🥕",
        "Planté un árbol en mi jardín 🌳"
      ];
      
      const randomUser = users[Math.floor(Math.random() * users.length)];
      const randomAction = actions[Math.floor(Math.random() * actions.length)];
      const actionTypes = ["transport", "food", "energy"] as const;
      
      return {
        user: { 
          name: randomUser, 
          username: randomUser.toLowerCase().replace(" ", "_"), 
          avatar: undefined 
        },
        content: randomAction,
        co2Impact: Math.round((Math.random() * 2 + 0.5) * 10) / 10,
        actionType: actionTypes[Math.floor(Math.random() * actionTypes.length)],
        likes: Math.floor(Math.random() * 20),
        comments: Math.floor(Math.random() * 8),
        isLiked: false,
        timestamp: "ahora",
        hasSustainableAction: true,
      };
    };

    intervalRef.current = setInterval(() => {
      const newPost = generateRandomPost();
      setAutoGeneratedPosts(prev => [newPost, ...prev.slice(0, 9)]); // Keep max 10 auto posts
    }, 10000); // Changed from 5000 to 10000 (10 seconds)

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
      }
    };
  }, [currentUser]);

  // Clean up auto-generated posts when page is closed/user logs out
  useEffect(() => {
    const handleBeforeUnload = () => {
      setAutoGeneratedPosts([]);
      localStorage.removeItem('ecoways-user');
    };

    window.addEventListener('beforeunload', handleBeforeUnload);
    return () => {
      window.removeEventListener('beforeunload', handleBeforeUnload);
      if (intervalRef.current) {
        clearInterval(intervalRef.current);
      }
    };
  }, []);

  // Combine original posts with auto-generated posts
  const allPosts = currentUser ? [...autoGeneratedPosts, ...posts] : mockPosts;

  const carbonData = {
    total: 12.4,
    weeklyChange: -15,
    monthlyGoal: 50,
    streak: 7,
    breakdown: {
      transport: 4.2,
      food: 3.8,
      energy: 2.1,
      shopping: 2.3,
    },
  };

  const userProfile = currentUser ? {
    user: {
      name: currentUser.name,
      username: currentUser.username,
      avatar: currentUser.avatar,
      bio: `Apasionado por un futuro sostenible 🌱 | Reduciendo mi huella de carbono día a día | Córdoba, Argentina`,
      location: "Córdoba, Argentina",
      joinedDate: "hoy",
      stats: {
        posts: posts.length,
        followers: Math.floor(Math.random() * 200 + 50),
        following: Math.floor(Math.random() * 150 + 30),
        totalCO2Saved: Math.round((Math.random() * 30 + 10) * 10) / 10,
      },
      badges: [
        {
          id: "1",
          name: "EcoStarter",
          description: "Registraste tu primera acción",
          icon: "🌱",
          rarity: "common" as const,
        },
        {
          id: "2", 
          name: "Nuevo Usuario",
          description: "Te uniste a la comunidad",
          icon: "✨",
          rarity: "common" as const,
        },
      ],
    },
    posts: posts.slice(0, 2),
  } : {
    user: {
      name: "Usuario Demo",
      username: "demo_user",
      avatar: undefined,
      bio: "Perfil de demostración",
      location: "Córdoba, Argentina", 
      joinedDate: "demo",
      stats: { posts: 0, followers: 0, following: 0, totalCO2Saved: 0 },
      badges: [],
    },
    posts: [],
  };

  const trendingTags = ["veganismo", "transporte", "energia", "reciclaje", "sostenible", "plantbased"];

  const handleLogin = (username: string) => {
    const user = {
      name: username,
      username: username.toLowerCase().replace(/\s+/g, "_"),
      avatar: undefined,
    };
    setCurrentUser(user);
    localStorage.setItem('ecoways-user', JSON.stringify(user));
  };

  const handleCreatePost = (content: string) => {
    if (!currentUser) return;
    
    const actionTypes = ["transport", "food", "energy"] as const;
    const randomAction = actionTypes[Math.floor(Math.random() * actionTypes.length)];
    
    const newPost = {
      user: { 
        name: currentUser.name, 
        username: currentUser.username, 
        avatar: currentUser.avatar 
      },
      content,
      co2Impact: Math.round((Math.random() * 3 + 0.5) * 10) / 10,
      actionType: randomAction,
      likes: 0,
      comments: 0,
      isLiked: false,
      timestamp: "ahora",
      hasSustainableAction: true,
    };
    setPosts([newPost, ...posts]);
  };

  const handleRegisterAction = () => {
    setShowRegisterModal(true);
  };

  const handleActionSaved = (savedCo2: number) => {
    toast({
      title: "¡Acción registrada!",
      description: `Ahorraste ${savedCo2} kg CO₂. ¡Excelente trabajo!`
    });
  };

  const handleActionShared = (content: string) => {
    if (!currentUser) return;
    
    const newPost = {
      user: { 
        name: currentUser.name, 
        username: currentUser.username, 
        avatar: currentUser.avatar 
      },
      content,
      co2Impact: 0,
      actionType: "transport" as const,
      likes: 0,
      comments: 0,
      isLiked: false,
      timestamp: "ahora",
      hasSustainableAction: true,
    };
    
    setPosts([newPost, ...posts]);
    
    toast({
      title: "¡Acción compartida!",
      description: "Tu acción sostenible fue publicada en el feed"
    });
  };

  const handleSearch = (query: string) => {
    console.log("Searching for:", query);
  };

  const renderContent = () => {
    switch (activeTab) {
      case "feed":
        return (
          <FeedSection
            posts={allPosts}
            currentUser={currentUser}
            onCreatePost={handleCreatePost}
          />
        );
      case "explore":
        return (
          <ExploreSection
            posts={allPosts}
            trendingTags={trendingTags}
            onSearch={handleSearch}
          />
        );
      case "footprint":
        return (
          <CarbonDashboard
            data={carbonData}
            onRegisterAction={handleRegisterAction}
          />
        );
      case "profile":
        return (
          <UserProfile
            {...userProfile}
            isOwnProfile={true}
          />
        );
      default:
        return null;
    }
  };

  return (
    <div className="min-h-screen bg-background font-inter">
      {/* Login Modal */}
      <LoginModal 
        open={!currentUser}
        onLogin={handleLogin}
      />

      <Navigation activeTab={activeTab} onTabChange={handleTabChange} />
      
      {/* Main Content */}
      <main className="pt-16 md:pt-20 pb-20 md:pb-8" role="main">
        <div className="container mx-auto max-w-2xl px-4 sm:px-6 lg:px-8">
          {currentUser && renderContent()}
        </div>
      </main>

      {/* Floating Action Button */}
      {currentUser && <FloatingActionButton onClick={() => setShowRegisterModal(true)} />}

      {/* Register Action Modal */}
      <RegisterActionModal
        open={showRegisterModal}
        onOpenChange={setShowRegisterModal}
        onActionSaved={handleActionSaved}
        onActionShared={handleActionShared}
      />
    </div>
  );
};

export default Index;